### ISSUE TITLE
PartialSourcePosition only contains a CompilationUnit error

### ISSUE THREAD

**Issue by khaes-kth** [algomaster99/collector-sahab#49]
Running bribe-sahab with depth=1 on https://github.com/khaes-kth/drr-execdiff/commit/396f09be09422635ef116c107da72f47bafdf2b1, gives the following:

```
Exception in thread "main" java.lang.UnsupportedOperationException: PartialSourcePosition only contains a CompilationUnit
        at spoon.reflect.cu.position.NoSourcePosition.getLine(NoSourcePosition.java:46)
        at se.kth.debug.MatchedLineFinder.lambda$getDiffLines$0(MatchedLineFinder.java:74)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
        at se.kth.debug.MatchedLineFinder.getDiffLines(MatchedLineFinder.java:71)
        at se.kth.debug.MatchedLineFinder.main(MatchedLineFinder.java:44)
java.lang.RuntimeException: method-name.txt (No such file or directory)
        at se.kth.debug.EventProcessor.parseMethodsForExitEvent(EventProcessor.java:112)
        at se.kth.debug.EventProcessor.<init>(EventProcessor.java:35)
        at se.kth.debug.Collector.invoke(Collector.java:87)
        at se.kth.debug.Collector.call(Collector.java:70)
        at se.kth.debug.Collector.call(Collector.java:12)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at se.kth.debug.Collector.main(Collector.java:62)
java.lang.RuntimeException: method-name.txt (No such file or directory)
        at se.kth.debug.EventProcessor.parseMethodsForExitEvent(EventProcessor.java:112)
        at se.kth.debug.EventProcessor.<init>(EventProcessor.java:35)
        at se.kth.debug.Collector.invoke(Collector.java:87)
        at se.kth.debug.Collector.call(Collector.java:70)
        at se.kth.debug.Collector.call(Collector.java:12)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at se.kth.debug.Collector.main(Collector.java:62)
                                                                                                                                                                                         130,2-9       Bot
```

**Comment by algomaster99** [comment]
GumTree spoon is responsible for this error. I will have a look tomorrow.

**Comment by algomaster99** [comment]
Fixed in https://github.com/algomaster99/collector-sahab/commit/226b65fd69669599419300a2afa73e67e290fd90.

**Comment by algomaster99** [comment]
I get really worried when I modify `MatchedLineFinder` because there are no tests for it. I hope the change in the linked commit won't alter other experiments drastically. I am working on writing tests for it.
