### ISSUE TITLE
IndexOutOfBoundException thrown

### ISSUE THREAD

**Issue by khaes-kth** [algomaster99/collector-sahab#65]
When bribe-sahab is run on commit `33837fa0d924e774200367acd9af74c391096080` of `drr-execdiff` project, I get the following:

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:459)
        at se.kth.debug.Debugger.setBreakpoints(Debugger.java:122)
        at se.kth.debug.EventProcessor.startEventProcessor(EventProcessor.java:46)
        at se.kth.debug.Collector.invoke(Collector.java:89)
        at se.kth.debug.Collector.call(Collector.java:76)
        at se.kth.debug.Collector.call(Collector.java:12)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at se.kth.debug.Collector.main(Collector.java:69)
```

**Comment by algomaster99** [comment]
`collector-sahab` tries to collect value at [158](https://github.com/khaes-kth/drr-execdiff/commit/33837fa0d924e774200367acd9af74c391096080#diff-2e9143c74f71576c5e6208a416df1a20c30e88af5c0167de828e9a1e1e459bf9R158). However, it is not an _executable_ line according to JDI. This seems weird.

**Comment by algomaster99** [comment]
> The availability of a line number for a location will depend on the level of debugging information available from the target VM. 

Reference: https://docs.oracle.com/javase/7/docs/jdk/api/jpda/jdi/com/sun/jdi/Location.html

So if it is illegal to put breakpoint on `while(true)`, it is because it is not available in the line number table generated by `javac` (openjdk 11.0.15 ) on my local. We need to work on understanding what criteria are applied on source lines for them to be a part of line number table in Java bytecode. Read [`4.7.12`](https://docs.oracle.com/javase/specs/jvms/se10/html/jvms-4.html).
